# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class COMMAND(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, command=None):  # noqa: E501
        """COMMAND - a model defined in Swagger

        :param command: The command of this COMMAND.  # noqa: E501
        :type command: str
        """
        self.swagger_types = {
            'command': str
        }

        self.attribute_map = {
            'command': 'command'
        }

        self._command = command

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The COMMAND of this COMMAND.  # noqa: E501
        :rtype: COMMAND
        """
        return util.deserialize_model(dikt, cls)

    @property
    def command(self):
        """Gets the command of this COMMAND.


        :return: The command of this COMMAND.
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this COMMAND.


        :param command: The command of this COMMAND.
        :type command: str
        """
        if command is None:
            raise ValueError("Invalid value for `command`, must not be `None`")  # noqa: E501

        self._command = command
